### ISSUE TITLE
Test the importer on macOS

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/gias-query-tool#11]
It appears that when running `make` on macOS, the [reencoding of the file](https://github.com/DFE-Digital/gias-query-tool/blob/master/Makefile#L25), done by `iconv` might fail.

This is probably due to an inconsistency between the versions of `iconv` available on Linux and macOS. If anyone with a Mac fancies trying this out please let me know the result here and I'll update the Makefile accordingly.

**Comment by neilgilmour** [comment]
I have both an Intel and M1 Mac. I remember having issues at some point in the process, but I'll start over and report back.
